services:
  code-server:
    image: ghcr.io/0xbigboss/vibe-station:latest
    platform: linux/amd64
    build: .
    stop_grace_period: 5s
    working_dir: /app
    privileged: true
    ports:
      - "${HOST_PORT:-}7080"
    environment:
      - SSH_AUTH_SOCK=/run/host-services/ssh-auth.sock
      - LANG=en_US.UTF-8
      - LC_ALL=en_US.UTF-8
      # Set XDG environment variables explicitly
      - XDG_CONFIG_HOME=/home/coder/.config
      - XDG_DATA_HOME=/home/coder/.local/share
      - XDG_STATE_HOME=/home/coder/.local/state
      - XDG_CACHE_HOME=/home/coder/.cache
    volumes:
      - ${CODE_SERVER_APP_DIR:-./}:/app
      - nix-data:/nix
      - coder-server-data:/home/coder/.local/share/code-server
      - coder-config-data:/home/coder/.config
      - coder-local-data:/home/coder/.local
      - coder-cache-data:/home/coder/.cache
      - coder-nix-profile:/home/coder/.nix-profile
      - /run/host-services/ssh-auth.sock:/run/host-services/ssh-auth.sock
      # Uncomment the following lines to enable Docker support using the host's Docker daemon
      # - /var/run/docker.sock:/var/run/docker.sock:rw
      - docker-images-data:/var/lib/docker
      - type: tmpfs
        target: /var/run
    healthcheck:
      test:
        [
          "CMD",
          "bash",
          "-c",
          "curl -f http://localhost:7080 || exit 1 && docker info || exit 1",
        ]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  # Example of adding a proxy to the code-server container
  # You can create an compose.override.yml file to extend or override the default compose file
  # Usage COMPOSE_FILE=compose.yml:compose.override.yml docker compose up -d
  # tilt:
  #   image: alpine/socat
  #   container_name: tilt
  #   restart: unless-stopped
  #   command: TCP-LISTEN:10350,fork,reuseaddr TCP:code-server:10350
  #   ports:
  #     - "10350"
  #   depends_on:
  #     - code-server

volumes:
  nix-data:
  coder-server-data:
  coder-config-data:
  coder-local-data:
  coder-cache-data:
  coder-nix-profile:
  docker-images-data:
