services:
  code-server:
    image: ghcr.io/0xbigboss/vibe-station:latest
    platform: linux/amd64
    build: .
    stop_grace_period: 5s
    working_dir: /app
    ports:
      - '${HOST_PORT:-}7080'
    environment:
      - SSH_AUTH_SOCK=/run/host-services/ssh-auth.sock
      - LANG=en_US.UTF-8
      - LC_ALL=en_US.UTF-8
      # Set XDG environment variables explicitly
      - XDG_CONFIG_HOME=/home/coder/.config
      - XDG_DATA_HOME=/home/coder/.local/share
      - XDG_STATE_HOME=/home/coder/.local/state
      - XDG_CACHE_HOME=/home/coder/.cache
      # Set ZSH history file location for persistence
      - HISTFILE=/commandhistory/.zsh_history
    volumes:
      - ${CODE_SERVER_APP_DIR:-./}:/app
      - nix-data:/nix
      - coder-server-data:/home/coder/.local/share/code-server
      - coder-config-data:/home/coder/.config
      - coder-local-data:/home/coder/.local
      - coder-cache-data:/home/coder/.cache
      - coder-nix-profile:/home/coder/.nix-profile
      - commandhistory:/commandhistory
      - /run/host-services/ssh-auth.sock:/run/host-services/ssh-auth.sock
      - /var/run/docker.sock:/var/run/docker.sock
    healthcheck:
      test: ['CMD', 'bash', '-c', 'curl -f http://localhost:7080 || exit 1']
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 60s

volumes:
  nix-data:
  coder-server-data:
  coder-config-data:
  coder-local-data:
  coder-cache-data:
  coder-nix-profile:
  commandhistory:
