services:
  code-server:
    image: 0xbigboss/vibe-station:latest
    platform: linux/amd64
    build: .
    stop_grace_period: 30s
    working_dir: /app
    privileged: true
    ports:
      - "${HOST_PORT:-}7080"
    volumes:
      - ${APP_DIR:-./}:/app
      - nix-data:/nix
      - coder-server-data:/home/coder/.local/share/code-server
      - docker-images-data:/var/lib/docker
      - type: tmpfs
        target: /var/run
    healthcheck:
      test:
        [
          "CMD",
          "bash",
          "-c",
          "curl -f http://localhost:7080 || exit 1 && docker info || exit 1",
        ]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

volumes:
  nix-data:
  coder-server-data:
  docker-images-data:
