services:
  code-server:
    platform: linux/amd64
    build: .
    stop_grace_period: 0s
    working_dir: /app
    ports:
      - "7080"
    volumes:
      - ${APP_DIR:-./}:/app
      - nix-store-data:/nix/store
      - coder-server-data:/home/coder/.local/share/code-server
      - docker-images-data:/var/lib/docker

volumes:
  nix-store-data:
  coder-server-data:
  docker-images-data:
