services:
  code-server:
    platform: linux/amd64
    build: .
    stop_grace_period: 0s
    working_dir: /app
    command: nix develop --command code-server --bind-addr 0.0.0.0:7080 --auth none
    ports:
      - "7080"
    volumes:
      - .:/app
      - vibe-station-data:/nix/store

volumes:
  vibe-station-data:
