services:
  code-server:
    platform: linux/amd64
    build: .
    stop_grace_period: 0s
    working_dir: /app
    ports:
      - "7080"
    volumes:
      - .:/app
      - nix-store-data:/nix/store
      - coder-server-data:/root/.local/share/code-server

volumes:
  nix-store-data:
  coder-server-data:
